=== codesnaper/XML/book.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT book (isbn, title, author, publisher)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (author-nm, date-of-birth)>
<!ELEMENT author-nm (#PCDATA)>
<!ELEMENT date-of-birth (#PCDATA)>
<!ELEMENT publisher (publisher-nm, est-dt)>
<!ELEMENT publisher-nm (#PCDATA)>
<!ELEMENT est-dt (#PCDATA)>

=== codesnaper/XML/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "D:\Work\WebServices\Master\WS20170614\Xml\book.dtd">
<book>
	<isbn>isbn200</isbn>
	<title>let us c</title>
	<author>
		<author-nm>yaswanth</author-nm>
		<date-of-birth>1990-01-01</date-of-birth>
	</author>
	<publisher>
		<publisher-nm>wrox</publisher-nm>
		<est-dt>2001-01-01</est-dt>
	</publisher>
</book>
