=== codesnaper/XML/super-market.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT super-market (basket, payment-info)>
<!ELEMENT basket (veg|fruit)+>
<!ELEMENT veg (veg-name, weight)>
<!ELEMENT veg-name (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT fruit (fruit-name, units)>
<!ELEMENT fruit-name (#PCDATA)>
<!ELEMENT units (#PCDATA)>
<!ELEMENT payment-info (cash | card)>
<!ELEMENT cash (denomination+)>
<!ELEMENT denomination (cash-value, leafs)>
<!ELEMENT cash-value (#PCDATA)>
<!ELEMENT leafs (#PCDATA)>
<!ELEMENT card (card-no, card-holder-name)>
<!ELEMENT card-no (#PCDATA)>
<!ELEMENT card-holder-name (#PCDATA)>

=== codesnaper/XML/transport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE super-market SYSTEM "D:\Work\WebServices\Master\WS20170614\Xml\super-market.dtd">
<super-market>
	<basket>
		<veg>
			<veg-name>cabage</veg-name>
			<weight>1</weight>
		</veg>
		
		<fruit>
			<fruit-name>apple</fruit-name>
			<units>1</units>
		</fruit>
						<fruit>
			<fruit-name>apple</fruit-name>
			<units>1</units>
		</fruit>


		<veg>
			<veg-name>cabage</veg-name>
			<weight>1</weight>
		</veg>
	</basket>
	<payment-info>
		<card>
			<card-no>2422535353</card-no>
			<card-holder-name>john</card-holder-name>
		</card>	
	</payment-info>
</super-market>
