=== codesnaper/XML/Xsd/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="name" type="xs:string"/>
	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="isbn" type="xs:string"/>
				<xs:element name="title" type="xs:string"/>
				<xs:element name="author">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="name"/>
							<xs:element name="dob" type="xs:date"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="publisher">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="name"/>
							<xs:element name="est-dt" type="xs:date"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== codesnaper/XML/Xsd/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Work/WebServices/Master/WS20170614/Xml/Xsd/book.xsd">
	<isbn>isbn03</isbn>
	<title>let us c</title>
	<author>		
		<name>yaswanth</name>		
		<dob>2016-01-01</dob>
	</author>
	<publisher>
		<name>Wrox</name>
		<est-dt>1998-01-01</est-dt>
	</publisher>
</book>
