=== codesnaper/XML/Xsd/gas-station.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="day-seltment" type="day-setlement-type"/>
	<xs:complexType name="day-setlement-type">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="fuel" type="fuelType"/>
			<xs:element name="consumable" type="consumableType"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="fuelType">
		<xs:sequence>
			<xs:element name="fuel-type" type="xs:string" nillable="false" minOccurs="0"/>
			<xs:element name="units" type="xs:int"/>
			<xs:element name="amount" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="consumableType">
		<xs:sequence>
			<xs:element name="product-name" type="xs:string"/>
			<xs:element name="units" type="xs:int"/>
			<xs:element name="amount" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== codesnaper/XML/Xsd/gas-station.xml
<?xml version="1.0" encoding="UTF-8"?>
<day-seltment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Work/WebServices/Master/WS20170614/Xml/Xsd/gas-station.xsd">
	<fuel>
		<fuel-type>Petrol</fuel-type>
		<units>1</units>
		<amount>76</amount>
	</fuel>
	<fuel>
		<fuel-type>Petrol</fuel-type>
		<units>1</units>
		<amount>76</amount>
	</fuel>
	<consumable>
		<product-name>Coke</product-name>
		<units>1</units>
		<amount>60</amount>
	</consumable>
	<fuel>		
		<units>1</units>
		<amount>76</amount>
	</fuel>
</day-seltment>
